#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# Mostra todas as combinações de cores possíveis no console.
# Também mostra os códigos ANSI para obter tais combinações.
# Uso: zzcores
# Ex.: zzcores
#
# Autor: Aurelio Marinho Jargas, www.aurelio.net
# Desde: 2001-12-11
# Versão: 1
# Tags: cores, tabela
# ----------------------------------------------------------------------------
# type zzcores
zzcores ()
{
	# zzzz -h cores "$1" && return
	case "$1" in -h|--help) zzajuda zzcores; return;; esac

	local frente fundo negrito cor

	for frente in 0 1 2 3 4 5 6 7
	do
		for negrito in '' ';1' # alterna entre linhas sem e com negrito
		do
			for fundo in 0 1 2 3 4 5 6 7
			do
				# Compõe o par de cores: NN;NN
				cor="4$fundo;3$frente"

				# Mostra na tela usando caracteres de controle: ESC[ NN m
				printf "\033[$cor${negrito}m $cor${negrito:-  } \033[m"
			done
			echo
		done
	done
}
# type zzcores
# zzzz -h zzcores "$@" || zzcores "$@"
# zzzz --init zzcores "$@" || #&& zzcores "$@"
#^executavel, nao funcao

# case "$1" in
# 	-h | --help) zzajuda zzcores;;
# 	--source) :;;
# 	*) zzcores "$@"
# esac

test "$0" = 'bash' || zzcores "$@"

# não é pro usuário dar source diretamente nesse arquivo. vai dar zika se as demais zz estiverem no path dele. aí o único use-case é o core sa zz dando source, aí posso passar um --source pra identificar (ou até mesmo remover a linha que chama a função, whatever)
