#!/usr/bin/env bash
debug=0
values=1
tests=(
2000	t	"2000 é bissexto"
2001	t	"2001 não é bissexto"
2002	t	"2002 não é bissexto"
2003	t	"2003 não é bissexto"
2004	t	"2004 é bissexto"
2005	t	"2005 não é bissexto"
2006	t	"2006 não é bissexto"
2007	t	"2007 não é bissexto"
2008	t	"2008 é bissexto"
2009	t	"2009 não é bissexto"
2010	t	"2010 não é bissexto"
2011	t	"2011 não é bissexto"
2012	t	"2012 é bissexto"

# Epoch
1968	t	"1968 é bissexto"
1969	t	"1969 não é bissexto"
1970	t	"1970 não é bissexto"
1971	t	"1971 não é bissexto"
1972	t	"1972 é bissexto"

# Divisível por 100 e não divisível por 4 não é
1900	t	"1900 não é bissexto"

# Erros
01/01/1970	t	"Ano inválido '01/01/1970'"
-2000 		t	"Ano inválido '-2000'"
foo 		t	"Ano inválido 'foo'"

)
. _lib
