#!/usr/bin/env bash
debug=0
values=3
tests=(
# basico
1	+	1	t	2
1	-	1	t	0
# 1	\*	1	t	1	# Nao tem como :/ -- "$var2" ?
1	/	1	t	1,00

# scale
1.0	+	1	t	2,0
1,0	+	1	t	2,0
1.10	+	1	t	2,10
1,10	+	1	t	2,10
10	/	3	t	3,33
2,20	+	3.30	t	5,50

# tudo junto
1+1	''	''	t	2
1+	1	''	t	2
1	+1	''	t	2
''	1+1	''	t	2
''	''	1+1	t	2

# other
.5	+	.5	t	1,0
,5	+	,5	t	1,0
1	+	.5	t	1,5
)
. _lib
