#!/bin/bash
debug=0
values=1
#TODO como testar a saida do comando? Achar um arquivo pequeno
tests=(
_fake_	r	"N.o consegui ler o arquivo /usr/include/_fake_.h"
/_fake_	r	"N.o consegui ler o arquivo /_fake_"
''	r	^Uso:.*
)
. _lib
