#!/usr/bin/env bash
debug=1
values=5
tests=(

# erros de sintaxe
''	''	''	''	''	r	^Uso:.*
-t	''	''	''	''	r	^Uso:.*
-d	''	''	''	''	r	^Uso:.*
-t	x	''	''	''	r	^Uso:.*
-d	x	''	''	''	r	^Uso:.*
-t	fulano@example.com	''	''	''	r	^Uso:.*
-d	fulano@example.com	''	''	''	r	^Uso:.*
-t	500	-d	fulano@example.com	''	r	^Uso:.*
-d	mm	-t	fulano@example.com	''	r	^Uso:.*
# erros de argumentos
-t	x	fulano@example.com	''	''	t	'Número inválido para a opção -t: x'
-t	-1	fulano@example.com	''	''	t	'Número inválido para a opção -t: -1'
-t	0	fulano@example.com	''	''	t	'Número inválido para a opção -t: 0'
-t	999	fulano@example.com	''	''	t	'O tamanho máximo para a imagem é 512'
-d	1	fulano@example.com	''	''	t	"Valor inválido para a opção -d: '1'"

# ignore case
fulano@example.com	''	''	''	''	t	'http://www.gravatar.com/avatar/98812691b923b99459c5231bc9725003'
FULANO@EXAMPLE.COM	''	''	''	''	t	'http://www.gravatar.com/avatar/98812691b923b99459c5231bc9725003'

# uso normal
-t	1	fulano@example.com	''	''	t	'http://www.gravatar.com/avatar/98812691b923b99459c5231bc9725003?size=1'
-t	500	fulano@example.com	''	''	t	'http://www.gravatar.com/avatar/98812691b923b99459c5231bc9725003?size=500'
-d	mm	fulano@example.com	''	''	t	'http://www.gravatar.com/avatar/98812691b923b99459c5231bc9725003?default=mm'
-d	retro	fulano@example.com	''	''	t	'http://www.gravatar.com/avatar/98812691b923b99459c5231bc9725003?default=retro'
-t	500	-d	mm	fulano@example.com	t	'http://www.gravatar.com/avatar/98812691b923b99459c5231bc9725003?size=500&default=mm'
-t	500	-d	retro	fulano@example.com	t	'http://www.gravatar.com/avatar/98812691b923b99459c5231bc9725003?size=500&default=retro'

)
. _lib
