#!/bin/bash
debug=0
values=1
tests=(

# mapa completo (ida e volta)
ABCDEFGHIJKLMNOPQRSTUVWXYZ	t	NOPQRSTUVWXYZABCDEFGHIJKLM
abcdefghijklmnopqrstuvwxyz	t	nopqrstuvwxyzabcdefghijklm
NOPQRSTUVWXYZABCDEFGHIJKLM	t	ABCDEFGHIJKLMNOPQRSTUVWXYZ
nopqrstuvwxyzabcdefghijklm	t	abcdefghijklmnopqrstuvwxyz

# e os acentos?
AÁaá	t	NÁná
)
. _lib
