#!/bin/sh
# run - run tests
#
# Usage:
#   ./run zzsenha.sh zzcores.sh   # test zzsenha and zzcores
#   ./run                         # run all tests

script_dir=$(dirname "$0")
zz_root=$(cd "$script_dir"; cd ..; pwd)  # handles absolute and relative
tmp='run.tmp'
tester='doctest.sh'

# Check requirements
$tester -V > /dev/null || {
	printf '%s\n' "Ops... Não achei o programa testador: $tester"
	printf '%s\n' 'Baixe-o deste endereço:'
	printf '%s\n' 'https://raw.github.com/aureliojargas/?????/master/?????.sh'
	exit 1
}

# Create temporary file with ZZ init in full paths
cat > "$tmp" <<EOF
. "$zz_root"/funcoeszz \\
	--cor 0 \\
	--path "$zz_root"/funcoeszz \\
	--dir  "$zz_root"/zz
EOF

if test $# -gt 0
then
	# Test specific file(s)
	"$tester" --include "$tmp" "$@"
else
	# Test all files
	"$tester" --include "$tmp" zz*.sh
fi

rm "$tmp"
