#!/usr/bin/env bash
debug=0
values=1
tests=(
0	t	''
1	r	'^[A-Za-z0-9]$'
10	r	'^[A-Za-z0-9]{10}$'
62	r	'^[A-Za-z0-9]{62}$'
''	r	'^[A-Za-z0-9]{8}$' # default

FOO	t	"Número inválido 'FOO'"
-8	t	"Número inválido '-8'"
63	t	"O tamanho máximo desse tipo de senha é 62"
)
. _lib
