#!/usr/bin/env bash

zz=../funcoeszz

# Go to tests folder
cd $(dirname "$0")

todas_as_funcoes=$(grep ^zz "$zz" | cut -d' ' -f1 | sed 's/^zz//' | sort)

funcoes_testadas=$(
	(
	# Locais
	ls -1 | egrep -v 'internet|funcoeszz|run|stats|_|\.'

	# Internet
	sed '1,/^tests="/d;/^"/,$ d' internet/run |
	"$zz" limpalixo |
	cut -d: -f1 |
	cut -d- -f1 | sort | uniq
	) | sort
)

falta_testar=$(diff <(echo "$todas_as_funcoes") <(echo "$funcoes_testadas") |	sed -n 's/^< //p')

echo Total: $(echo "$todas_as_funcoes" | wc -l) funções, $(echo "$funcoes_testadas" | wc -l) testadas.
echo Funções que falta testar \($(echo "$falta_testar" | wc -l)\):
echo "$falta_testar"

# echo ---------------
# echo "$todas_as_funcoes"
# echo ---------------
# echo "$funcoes_testadas"


