#!/bin/bash

temp="_trocapalavra"
cp _dados $temp

debug=0
values=3
tests=(
''	''	''	r	^Uso:.*
dois	''	''	r	^Uso:.*
dois	DOIS	''	r	^Uso:.*
dois	DOIS	_fake_	r	"N.o consegui ler o arquivo _fake_"
dois	DOIS	$temp	t	"Feito $temp"
)
. _lib

############################################################################

# Testes personalizados

# Troca simples
result=$(sed s/dois/DOIS/g _dados | diff - $temp | grep '^[<>]')
if [ "$result" ]
then
	echo "ERROR: trocapalavra dois DOIS $temp (conteúdo)"
	echo "$result"
fi

# Troca global
cp _dados $temp
$zz trocapalavra : ' ' $temp > /dev/null
result=$(sed 's/:/ /g' _dados | diff - $temp | grep '^[<>]')
if [ "$result" ]
then
	echo "ERROR: trocapalavra dois DOIS $temp (conteúdo, global)"
	echo "$result"
fi

rm -f $temp