$ zzzz -h

zzzz
Mostra informações sobre as funções, como versão e localidade.
Opções: --atualiza  baixa a versão mais nova das funções
        --teste     testa se a codificação e os pré-requisitos estão OK
        --bashrc    instala as funções no ~/.bashrc
        --tcshrc    instala as funções no ~/.tcshrc
        --zshrc     instala as funções no ~/.zshrc
Uso: zzzz [--atualiza|--teste|--bashrc|--tcshrc|--zshrc]
Ex.: zzzz
     zzzz --teste

$ zzzz --teste | sed 's/\.\.\. .*/.../;/Atenção/,/^Talvez/d;/^ *$/d'
Procurando o comando awk...
Procurando o comando bc...
Procurando o comando cat...
Procurando o comando chmod...
Procurando o comando clear...
Procurando o comando cp...
Procurando o comando cpp...
Procurando o comando curl...
Procurando o comando cut...
Procurando o comando diff...
Procurando o comando du...
Procurando o comando find...
Procurando o comando fmt...
Procurando o comando grep...
Procurando o comando iconv...
Procurando o comando links...
Procurando o comando elinks...
Procurando o comando lynx...
Procurando o comando mktemp...
Procurando o comando mv...
Procurando o comando od...
Procurando o comando ps...
Procurando o comando rm...
Procurando o comando sed...
Procurando o comando sleep...
Procurando o comando sort...
Procurando o comando tail...
Procurando o comando tr...
Procurando o comando uniq...
Verificando a codificação do sistema...
Verificando a codificação das Funções ZZ...
$ zzzz | awk '/^\(/ {sub(/\) .*/,")"); gsub(/[0-9]*/,""); print}'
(script)
( pasta)
(versão)
( cores)
(   tmp)
(bashrc)
( zshrc)
(  base)
(  site)
((  funções disponíveis ))
$
