#!/bin/bash
# 2011-05-18
# Aurelio Jargas

cd $(dirname $0) || exit 1

### Não edite este script!
### O código abaixo foi gerado pelo index.php,
### quando descomentado o trecho @scriptgen
###
### Atualize cada vez que uma função nova for adicionada/removida do menu

ZZDIR=../../zz ZZOFF='zzanatel zzarrumanome zzbeep zzblist zzbolsas zzbrasileirao zzcbn zzchavepgp zzchecamd5 zzcinclude zzcinemais zzcinemark15h zzcineuci zzcores zzcorrida zzdefine zzdefinr zzdelicious zzdetransp zzdicasl zzdicbabelfish zzdicbabylon zzdicesperanto zzdicjargon zzdicportugues zzdicportugues2 zzdictodos zzdiffpalavra zzdolar zzdominiopais zzecho zzenglish zzenviaemail zzeuro zzextensao zzfeed zzferiado zzfrenteverso2pdf zzfreshmeat zzglobo zzgoogle zzhoracerta zzhowto zzipinternet zzjquery zzkill zzlembrete zzletrademusica zzlinux zzlinuxnews zzlocale zzloteria zzloteria2 zzmaiores zzminiurl zzmoeda zzmoneylog zzmudaprefixo zznarrativa zznatal zznome zznomefoto zznoticiaslinux zznoticiassec zzora zzpiada zzpronuncia zzquebramd5 zzramones zzrandbackground zzrastreamento zzrelansi zzrpmfind zzsecurity zzsigla zzss zztempo zztradutor zztrocaarquivos zztrocaextensao zztrocapalavra zztv zztweets zzunix2dos zzwhoisbr zzwikipedia' ../../funcoeszz --tudo-em-um > funcoeszz

echo Gravado $PWD/funcoeszz
